# Notes on Notation

In [1]:
import numpy as np

In [2]:
nd = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7],
])

In [3]:
nd[0,0] # Row 0, Col 0

1

In [4]:
nd[3,2] # Row 3, Col 2

6

In [5]:
nd[0:3,1:3] # First up to fourth row, Second and third column

array([[2, 3],
       [3, 4],
       [4, 5]])

In [6]:
nd[:, 3] # All rows, fourth column

array([4, 5, 6, 7])

In [7]:
nd[-1, 1:3] # Last row, second up and third column

array([5, 6])

# Creating Numpy Arrays

List to 1D array:

In [8]:
np.array([2,3,4])

array([2, 3, 4])

List of tuples to 2D array:

In [9]:
np.array([(2,3,4), (5,6,7)])

array([[2, 3, 4],
       [5, 6, 7]])

# Arrays with Initial Values

Create an empty array:

In [10]:
np.empty(5)

array([ -3.10503618e+231,  -3.10503618e+231,   2.24817709e-314,
         2.24818020e-314,   2.24818023e-314])

You can also specify the rows and columns:

In [11]:
np.empty((5,4))

array([[ -3.10503618e+231,  -3.10503618e+231,   6.94529424e-310,
          6.94529425e-310],
       [  2.23470618e-314,   2.24337878e-314,   2.29568061e+286,
          6.36777671e+150],
       [ -3.10503618e+231,  -3.10503618e+231,  -4.04928275e-254,
          1.47764914e+228],
       [ -3.10503618e+231,  -3.10503618e+231,  -3.10503618e+231,
         -3.10503618e+231],
       [  6.94529554e-310,   1.06099790e-313,   6.94529554e-310,
          1.39077726e-309]])

The values in the empty array correspond to the existing values in the memory location that was used.

Create an array full of `1` values:

In [12]:
np.ones((5,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

# Specify the datatype

In [13]:
np.ones((5,4), dtype=np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

The default data type is float, but you can specify otherwise.

# Generating random numbers

In [15]:
np.random.random((5,4))

array([[ 0.48759544,  0.08250419,  0.31118894,  0.25903986],
       [ 0.49155065,  0.91812417,  0.53735098,  0.63733769],
       [ 0.15461294,  0.35481781,  0.42100426,  0.33616596],
       [ 0.69811628,  0.12378027,  0.09068895,  0.19826146],
       [ 0.93288978,  0.4606915 ,  0.84622427,  0.26639156]])

You can also use `numpy.random.rand`, `numpy.random.normal` (for a normal distribution), and `numpy.random.randint` for a uniform distribution of integers.

Using `numpy.random.rand` is a bit easier but is less idiomatic:

In [17]:
np.random.rand(5,4)

array([[ 0.46738822,  0.28022667,  0.63302457,  0.56937143],
       [ 0.25515446,  0.76538109,  0.4813825 ,  0.81390542],
       [ 0.95988555,  0.22112334,  0.73524916,  0.5849861 ],
       [ 0.42772851,  0.77341581,  0.02931847,  0.09674343],
       [ 0.46373663,  0.95250406,  0.9693177 ,  0.69852659]])

Using a Gaussian (normal) sample results in a distribution of items with a mean of 0 and a standard deviation of 1:

In [20]:
np.random.normal(size=(2,3))

array([[-1.055064  ,  0.02199569,  0.19458479],
       [ 0.56816255,  0.416728  ,  0.14486431]])

You can also specify a mean and standard deviation:

In [22]:
np.random.normal(50, 25, size=(2,3))

array([[ 29.74691094,  27.17454602,  86.66795823],
       [ 84.42407554,  37.18812593,  63.37487722]])

You can use `np.random.randint` to generate random integers between ranges:

In [30]:
print np.random.randint(10) # assumed to be 0,10
print np.random.randint(0, 10)
print np.random.randint(0, 10, size=5) # 1D array of 5 integers b/n 0, 10
print np.random.randint(0, 10, size=(2,3)) # a 2x3 array of random integers b/n 0, 10

9
7
[9 3 8 8 7]
[[1 2 9]
 [4 9 3]]


# Array attributes

`shape` will give you the "shape" (number of rows and columns) of an array:

In [36]:
a = np.ones((3,5))

In [40]:
print a.shape
print a.shape[0] # number of rows
print a.shape[1] # number of columns
print len(a.shape) # number of dimensions

(3, 5)
3
5
2


`size` will give you the total number of elements:

In [39]:
print a.size

15


`dtype` will tell you the data type of the elements in the array:

In [41]:
print a.dtype

float64


# Operations on ndarrays

In [43]:
np.random.seed(693)
a = np.random.randint(0, 10, size=(5,4))
print 'Array: \n', a

Array: 
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]


Sum all the elements of an array:

In [44]:
a.sum()

79

Summing columns and rows:

In [45]:
print a.sum(axis=0) # column
print a.sum(axis=1) # row

[25 15 25 14]
[ 8 12 21 24 14]


Min, max, and mean:

In [48]:
print a.min(axis=0) # min for each column
print a.max(axis=1) # max for each row
print a.mean() # Mean for all elements

[1 0 0 1]
[5 4 9 9 7]
3.95
