# Notes on Notation

In [1]:
import numpy as np

In [4]:
nd = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7],
])

In [5]:
nd[0,0] # Row 0, Col 0

1

In [6]:
nd[3,2] # Row 3, Col 2

6

In [7]:
nd[0:3,1:3] # First up to fourth row, Second and third column

array([[2, 3],
       [3, 4],
       [4, 5]])

In [8]:
nd[:, 3] # All rows, fourth column

array([4, 5, 6, 7])

In [9]:
nd[-1, 1:3] # Last row, second up and third column

array([5, 6])

# Quiz: Replace a slice